spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=utf-8&userSSL=false&allowMultiQueries=true
    username: root
    password: 1234
server:
  port: 8080
mybatis-plus:
  global-config:
      db-config:
        id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

